In [ ]:
import pandas as pd

weather = pd.read_excel('../Data/04.weather2023.xlsx', index_col='date')
weather.head()

            location loc_name  temp  rain  wind  humi  sunshine  cloud
date
2023-01-01       108       서울  -0.2   NaN   2.7  55.0       9.0    1.3
2023-01-02       108       서울  -4.5   NaN   2.5  46.0       9.1    0.0
2023-01-03       108       서울  -5.0   NaN   1.8  49.0       9.1    0.0
2023-01-04       108       서울  -1.8   NaN   1.9  51.0       8.7    1.9
2023-01-05       108       서울  -1.6   NaN   1.6  58.1       4.7    3.6

In [6]:
print(weather.isnull().sum())

location      0
loc_name      0
temp          0
rain        115
wind          0
humi          0
sunshine      0
cloud         0
dtype: int64

In [8]:
weather.drop(['rain', 'location', 'loc_name'], axis=1, inplace=True)
weather

            temp  wind  humi  sunshine  cloud
date
2023-01-01  -0.2   2.7  55.0       9.0    1.3
2023-01-02  -4.5   2.5  46.0       9.1    0.0
2023-01-03  -5.0   1.8  49.0       9.1    0.0
2023-01-04  -1.8   1.9  51.0       8.7    1.9
2023-01-05  -1.6   1.6  58.1       4.7    3.6
...          ...   ...   ...       ...    ...
2023-06-26  24.2   2.9  88.6       0.0   10.0
2023-06-27  25.3   3.2  73.1       6.8    6.5
2023-06-28  26.5   2.5  77.4       3.8    8.1
2023-06-29  24.2   2.3  95.4       0.0   10.0
2023-06-30  25.3   1.8  89.8       1.4    7.4

[181 rows x 5 columns]

In [11]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 181 entries, 2023-01-01 to 2023-06-30
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   temp      181 non-null    float64
 1   wind      181 non-null    float64
 2   humi      181 non-null    float64
 3   sunshine  181 non-null    float64
 4   cloud     181 non-null    float64
dtypes: float64(5)
memory usage: 12.6 KB